// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RhFolha.Infrastructure.Persistence;

#nullable disable

namespace RhFolha.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RhFolhaDbContext))]
    partial class RhFolhaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RhFolha.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DocumentNumber = "12345678000190",
                            IsActive = true,
                            LegalName = "ConsulCLT Demonstracao Ltda",
                            TradeName = "ConsulCLT"
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "InternalCode")
                        .IsUnique();

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalCode = "OPER",
                            IsActive = true,
                            Name = "Operacoes"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalCode = "ADM",
                            IsActive = true,
                            Name = "Administrativo"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalCode = "PROD",
                            IsActive = true,
                            Name = "Producao"
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("admission_date");

                    b.Property<decimal>("BaseSalary")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_salary");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompensationModel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("compensation_model");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_number");

                    b.Property<Guid>("JobPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_position_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<decimal>("ProductionUnitValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("production_unit_value");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("registration");

                    b.Property<Guid?>("ResponsibleEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_employee_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("ResponsibleEmployeeId");

                    b.HasIndex("CompanyId", "DocumentNumber")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Registration")
                        .IsUnique();

                    b.HasIndex("CompanyId", "ResponsibleEmployeeId");

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd01"),
                            AdmissionDate = new DateOnly(2022, 11, 1),
                            BaseSalary = 9500.00m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CompensationModel = "mensalista",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            DocumentNumber = "78912345608",
                            JobPositionId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            Name = "Roberto de Souza Carvalho",
                            ProductionUnitValue = 0m,
                            Registration = "0001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd02"),
                            AdmissionDate = new DateOnly(2025, 1, 20),
                            BaseSalary = 3200.00m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CompensationModel = "mensalista",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            DocumentNumber = "45678912304",
                            JobPositionId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            Name = "Mariana Costa Santos",
                            ProductionUnitValue = 0m,
                            Registration = "0002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd03"),
                            AdmissionDate = new DateOnly(2023, 8, 10),
                            BaseSalary = 0m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CompensationModel = "producao",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            DocumentNumber = "98765432100",
                            JobPositionId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            Name = "Ana Beatris Oliveira",
                            ProductionUnitValue = 12.50m,
                            Registration = "0003",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Employees.EmployeeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("responsible");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("CompanyId", "Status");

                    b.HasIndex("CompanyId", "Type");

                    b.HasIndex("CompanyId", "EmployeeId", "EventDate");

                    b.ToTable("employee_events", (string)null);
                });

            modelBuilder.Entity("RhFolha.Domain.JobPositions.JobPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cbo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cbo");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("internal_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "InternalCode")
                        .IsUnique();

                    b.ToTable("job_positions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            Cbo = "142105",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalCode = "GER-OPER",
                            IsActive = true,
                            Name = "Gerente de Operacoes"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            Cbo = "411010",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalCode = "ASS-ADM",
                            IsActive = true,
                            Name = "Assistente Administrativo"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            Cbo = "763210",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InternalCode = "COST-IND",
                            IsActive = true,
                            Name = "Costureira Industrial"
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.FixedPayrollEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RubricId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubric_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RubricId");

                    b.HasIndex("CompanyId", "EmployeeId");

                    b.HasIndex("CompanyId", "IsActive");

                    b.HasIndex("CompanyId", "RubricId");

                    b.ToTable("fixed_payroll_entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Amount = 180m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd01"),
                            IsActive = true,
                            Notes = "Plano de saude mensal",
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee06"),
                            StartsOn = new DateOnly(2026, 6, 1)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Amount = 192m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd02"),
                            IsActive = true,
                            Notes = "Vale transporte mensal",
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee05"),
                            StartsOn = new DateOnly(2026, 6, 1)
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("employee_count");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<Guid>("PayrollPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_period_id");

                    b.Property<string>("PeriodCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalDescontos")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_descontos");

                    b.Property<decimal>("TotalLiquido")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_liquido");

                    b.Property<decimal>("TotalProventos")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_proventos");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("CompanyId", "PayrollPeriodId", "IsCurrent");

                    b.ToTable("payroll_calculations", (string)null);
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollCalculationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("BaseAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_amount");

                    b.Property<decimal?>("CalculationRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("calculation_rate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("employee_name");

                    b.Property<string>("EmployeeRegistration")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("employee_registration");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origin");

                    b.Property<Guid>("PayrollCalculationId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_calculation_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("RubricCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rubric_code");

                    b.Property<Guid>("RubricId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubric_id");

                    b.Property<string>("RubricName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("rubric_name");

                    b.Property<string>("RubricType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rubric_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RubricId");

                    b.HasIndex("PayrollCalculationId", "EmployeeId");

                    b.HasIndex("PayrollCalculationId", "RubricId");

                    b.ToTable("payroll_calculation_items", (string)null);
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origin");

                    b.Property<Guid>("PayrollPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("payroll_period_id");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("quantity");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<Guid>("RubricId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubric_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("RubricId");

                    b.HasIndex("CompanyId", "PayrollPeriodId");

                    b.HasIndex("CompanyId", "EmployeeId", "PayrollPeriodId");

                    b.HasIndex("CompanyId", "RubricId", "PayrollPeriodId");

                    b.ToTable("payroll_entries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Amount = 800m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd02"),
                            EntryDate = new DateOnly(2026, 6, 15),
                            Notes = "Adiantamento quinzenal",
                            Origin = "manual",
                            PayrollPeriodId = new Guid("99999999-9999-9999-9999-999999999901"),
                            Reference = "ADV-06/2026",
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee03"),
                            Status = "aprovado"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Amount = 625m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd03"),
                            EntryDate = new DateOnly(2026, 6, 20),
                            Notes = "Producao parcial do mes",
                            Origin = "manual",
                            PayrollPeriodId = new Guid("99999999-9999-9999-9999-999999999901"),
                            Quantity = 50m,
                            Reference = "PROD-06/2026",
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee02"),
                            Status = "aprovado"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Amount = 180m,
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd01"),
                            EntryDate = new DateOnly(2026, 6, 30),
                            Notes = "Desconto plano de saude",
                            Origin = "manual",
                            PayrollPeriodId = new Guid("99999999-9999-9999-9999-999999999901"),
                            Reference = "SAUDE-06/2026",
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee06"),
                            Status = "aprovado"
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("payroll_periods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999901"),
                            Code = "2026-06",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndsOn = new DateOnly(2026, 6, 30),
                            Month = 6,
                            OpenedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartsOn = new DateOnly(2026, 6, 1),
                            Status = "aberta",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.Rubric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsFixedEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_fixed_entry");

                    b.Property<bool>("AllowsManualEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_manual_entry");

                    b.Property<bool>("AllowsMassEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_mass_entry");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ESocialNature")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("esocial_nature");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("rubrics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01"),
                            AllowsFixedEntry = false,
                            AllowsManualEntry = false,
                            AllowsMassEntry = false,
                            Code = "001",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ESocialNature = "1000",
                            IsActive = true,
                            Name = "Salario mensal",
                            Type = "provento"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee02"),
                            AllowsFixedEntry = false,
                            AllowsManualEntry = true,
                            AllowsMassEntry = true,
                            Code = "002",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ESocialNature = "1000",
                            IsActive = true,
                            Name = "Producao",
                            Type = "provento"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee03"),
                            AllowsFixedEntry = false,
                            AllowsManualEntry = true,
                            AllowsMassEntry = true,
                            Code = "101",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Adiantamento salarial",
                            Type = "provento"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee04"),
                            AllowsFixedEntry = false,
                            AllowsManualEntry = true,
                            AllowsMassEntry = true,
                            Code = "201",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Desconto de adiantamento",
                            Type = "desconto"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee05"),
                            AllowsFixedEntry = true,
                            AllowsManualEntry = true,
                            AllowsMassEntry = true,
                            Code = "202",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Vale transporte",
                            Type = "desconto"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee06"),
                            AllowsFixedEntry = true,
                            AllowsManualEntry = true,
                            AllowsMassEntry = true,
                            Code = "203",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Plano de saude",
                            Type = "desconto"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee07"),
                            AllowsFixedEntry = false,
                            AllowsManualEntry = false,
                            AllowsMassEntry = false,
                            Code = "901",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INSS",
                            Type = "desconto"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee08"),
                            AllowsFixedEntry = false,
                            AllowsManualEntry = false,
                            AllowsMassEntry = false,
                            Code = "902",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "IRRF",
                            Type = "desconto"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee09"),
                            AllowsFixedEntry = false,
                            AllowsManualEntry = false,
                            AllowsMassEntry = false,
                            Code = "903",
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "FGTS informativo",
                            Type = "informativa"
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.RubricValidity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CalculationBase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("calculation_base");

                    b.Property<string>("CalculationMethod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("calculation_method");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<bool>("IncidenceDsr")
                        .HasColumnType("boolean")
                        .HasColumnName("incidence_dsr");

                    b.Property<bool>("IncidenceFgts")
                        .HasColumnType("boolean")
                        .HasColumnName("incidence_fgts");

                    b.Property<bool>("IncidenceInss")
                        .HasColumnType("boolean")
                        .HasColumnName("incidence_inss");

                    b.Property<bool>("IncidenceIrrf")
                        .HasColumnType("boolean")
                        .HasColumnName("incidence_irrf");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RubricId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubric_id");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RubricId", "StartsOn")
                        .IsUnique();

                    b.ToTable("rubric_validities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff01"),
                            CalculationBase = "salario_base",
                            CalculationMethod = "sistema",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = true,
                            IncidenceFgts = true,
                            IncidenceInss = true,
                            IncidenceIrrf = true,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee01"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff02"),
                            CalculationBase = "producao",
                            CalculationMethod = "quantidade_valor",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = true,
                            IncidenceInss = true,
                            IncidenceIrrf = true,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee02"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff03"),
                            CalculationBase = "nenhuma",
                            CalculationMethod = "valor_fixo",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = false,
                            IncidenceInss = false,
                            IncidenceIrrf = false,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee03"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff04"),
                            CalculationBase = "nenhuma",
                            CalculationMethod = "valor_fixo",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = false,
                            IncidenceInss = false,
                            IncidenceIrrf = false,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee04"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff05"),
                            CalculationBase = "nenhuma",
                            CalculationMethod = "valor_fixo",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = false,
                            IncidenceInss = false,
                            IncidenceIrrf = false,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee05"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff06"),
                            CalculationBase = "nenhuma",
                            CalculationMethod = "valor_fixo",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = false,
                            IncidenceInss = false,
                            IncidenceIrrf = false,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee06"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff07"),
                            CalculationBase = "base_inss",
                            CalculationMethod = "sistema",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = false,
                            IncidenceInss = false,
                            IncidenceIrrf = false,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee07"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff08"),
                            CalculationBase = "base_irrf",
                            CalculationMethod = "sistema",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = false,
                            IncidenceInss = false,
                            IncidenceIrrf = false,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee08"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffff09"),
                            CalculationBase = "base_fgts",
                            CalculationMethod = "sistema",
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncidenceDsr = false,
                            IncidenceFgts = false,
                            IncidenceInss = false,
                            IncidenceIrrf = false,
                            IsActive = true,
                            RubricId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee09"),
                            StartsOn = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.StatutoryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "IsActive");

                    b.HasIndex("CompanyId", "Type", "StartsOn")
                        .IsUnique();

                    b.ToTable("statutory_tables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "INSS 2026",
                            Notes = "Tabela informada para parametrizacao de 2026. Teto: R$ 8.475,55. Revisar a fonte oficial antes de uso em producao.",
                            StartsOn = new DateOnly(2026, 1, 1),
                            Type = "inss"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "IRRF 2026",
                            Notes = "Tabela progressiva mensal publicada pela Receita Federal para fatos geradores a partir de janeiro de 2026.",
                            StartsOn = new DateOnly(2026, 1, 1),
                            Type = "irrf"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "IRRF reducao 2026",
                            Notes = "Regra redutora da Lei 15.270/2025: ate R$ 5.000,00 reduz ate R$ 312,89; de R$ 5.000,01 a R$ 7.350,00 aplica reducao = R$ 978,62 - 0,133145 x rendimentos tributaveis mensais.",
                            StartsOn = new DateOnly(2026, 1, 1),
                            Type = "irrf_reducao"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "FGTS mensal 2026",
                            Notes = "Deposito mensal de FGTS a cargo do empregador: 8% da remuneracao paga ou devida ao trabalhador CLT.",
                            StartsOn = new DateOnly(2026, 1, 1),
                            Type = "fgts"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            CompanyId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "FGTS saque-aniversario 2026",
                            Notes = "Tabela oficial de saque-aniversario para consulta. Nao compoe o calculo mensal da folha do empregador.",
                            StartsOn = new DateOnly(2026, 1, 1),
                            Type = "fgts_saque_aniversario"
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.StatutoryTableRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DeductionAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("deduction_amount");

                    b.Property<decimal>("LowerLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("lower_limit");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("rate_percent");

                    b.Property<Guid>("StatutoryTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("statutory_table_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("UpperLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("upper_limit");

                    b.HasKey("Id");

                    b.HasIndex("StatutoryTableId", "LowerLimit")
                        .IsUnique();

                    b.ToTable("statutory_table_ranges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 0m,
                            LowerLimit = 0m,
                            RatePercent = 7.5m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333301"),
                            UpperLimit = 1621.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 24.32m,
                            LowerLimit = 1621.01m,
                            RatePercent = 9.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333301"),
                            UpperLimit = 2902.84m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 111.40m,
                            LowerLimit = 2902.85m,
                            RatePercent = 12.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333301"),
                            UpperLimit = 4354.27m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 198.49m,
                            LowerLimit = 4354.28m,
                            RatePercent = 14.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333301"),
                            UpperLimit = 8475.55m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 0m,
                            LowerLimit = 0m,
                            RatePercent = 0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333302"),
                            UpperLimit = 2428.80m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 182.16m,
                            LowerLimit = 2428.81m,
                            RatePercent = 7.5m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333302"),
                            UpperLimit = 2826.65m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 394.16m,
                            LowerLimit = 2826.66m,
                            RatePercent = 15.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333302"),
                            UpperLimit = 3751.05m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 675.49m,
                            LowerLimit = 3751.06m,
                            RatePercent = 22.5m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333302"),
                            UpperLimit = 4664.68m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 908.73m,
                            LowerLimit = 4664.69m,
                            RatePercent = 27.5m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333302")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 312.89m,
                            LowerLimit = 0m,
                            RatePercent = 0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333303"),
                            UpperLimit = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444411"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 978.62m,
                            LowerLimit = 5000.01m,
                            RatePercent = 13.3145m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333303"),
                            UpperLimit = 7350.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444412"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 0m,
                            LowerLimit = 0m,
                            RatePercent = 8.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333304")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444413"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 0m,
                            LowerLimit = 0.01m,
                            RatePercent = 50.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333305"),
                            UpperLimit = 500.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444414"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 50.00m,
                            LowerLimit = 500.01m,
                            RatePercent = 40.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333305"),
                            UpperLimit = 1000.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444415"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 150.00m,
                            LowerLimit = 1000.01m,
                            RatePercent = 30.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333305"),
                            UpperLimit = 5000.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444416"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 650.00m,
                            LowerLimit = 5000.01m,
                            RatePercent = 20.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333305"),
                            UpperLimit = 10000.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444417"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 1150.00m,
                            LowerLimit = 10000.01m,
                            RatePercent = 15.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333305"),
                            UpperLimit = 15000.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444418"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 1900.00m,
                            LowerLimit = 15000.01m,
                            RatePercent = 10.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333305"),
                            UpperLimit = 20000.00m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444419"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeductionAmount = 2900.00m,
                            LowerLimit = 20000.01m,
                            RatePercent = 5.0m,
                            StatutoryTableId = new Guid("33333333-3333-3333-3333-333333333305")
                        });
                });

            modelBuilder.Entity("RhFolha.Domain.Security.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("user_email");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_role");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RhFolha.Domain.Security.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Role");

                    b.ToTable("system_users", (string)null);
                });

            modelBuilder.Entity("RhFolha.Domain.Departments.Department", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RhFolha.Domain.Employees.Employee", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Departments.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.JobPositions.JobPosition", "JobPosition")
                        .WithMany()
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Employees.Employee", "ResponsibleEmployee")
                        .WithMany()
                        .HasForeignKey("ResponsibleEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("JobPosition");

                    b.Navigation("ResponsibleEmployee");
                });

            modelBuilder.Entity("RhFolha.Domain.Employees.EmployeeEvent", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("EmployeeEvents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RhFolha.Domain.JobPositions.JobPosition", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("JobPositions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.FixedPayrollEntry", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("FixedPayrollEntries")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Payroll.Rubric", "Rubric")
                        .WithMany()
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollCalculation", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("PayrollCalculations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Payroll.PayrollPeriod", "PayrollPeriod")
                        .WithMany()
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("PayrollPeriod");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollCalculationItem", b =>
                {
                    b.HasOne("RhFolha.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Payroll.PayrollCalculation", "PayrollCalculation")
                        .WithMany("Items")
                        .HasForeignKey("PayrollCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Payroll.Rubric", "Rubric")
                        .WithMany()
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollCalculation");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollEntry", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("PayrollEntries")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Employees.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Payroll.PayrollPeriod", "PayrollPeriod")
                        .WithMany()
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RhFolha.Domain.Payroll.Rubric", "Rubric")
                        .WithMany()
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollPeriod", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("PayrollPeriods")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.Rubric", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("Rubrics")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.RubricValidity", b =>
                {
                    b.HasOne("RhFolha.Domain.Payroll.Rubric", "Rubric")
                        .WithMany("Validities")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.StatutoryTable", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", "Company")
                        .WithMany("StatutoryTables")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.StatutoryTableRange", b =>
                {
                    b.HasOne("RhFolha.Domain.Payroll.StatutoryTable", "StatutoryTable")
                        .WithMany("Ranges")
                        .HasForeignKey("StatutoryTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatutoryTable");
                });

            modelBuilder.Entity("RhFolha.Domain.Security.AuditLog", b =>
                {
                    b.HasOne("RhFolha.Domain.Security.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RhFolha.Domain.Security.SystemUser", b =>
                {
                    b.HasOne("RhFolha.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RhFolha.Domain.Companies.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("EmployeeEvents");

                    b.Navigation("Employees");

                    b.Navigation("FixedPayrollEntries");

                    b.Navigation("JobPositions");

                    b.Navigation("PayrollCalculations");

                    b.Navigation("PayrollEntries");

                    b.Navigation("PayrollPeriods");

                    b.Navigation("Rubrics");

                    b.Navigation("StatutoryTables");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.PayrollCalculation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.Rubric", b =>
                {
                    b.Navigation("Validities");
                });

            modelBuilder.Entity("RhFolha.Domain.Payroll.StatutoryTable", b =>
                {
                    b.Navigation("Ranges");
                });
#pragma warning restore 612, 618
        }
    }
}
